- packages/vue/package.json
- packages/vue/src/hooks/webpack.ts
- yarn.lock
> Webpack vue

- packages/scf-adapter/src/hooks/deploy.ts
fix(scf-adapter) 优化切换版本时函数状态的判断
> fix(scf-adapter) 优化切换版本时函数状态的判断

- packages/vue/src/hooks/webpack.ts
支持从yml中读取cache-loader和vue-loader的配置
> fix(vue) 支持从yml中读取cache-loader和vue-loader的配置

- packages/scf-adapter/src/hooks/cli.ts
- packages/scf-adapter/src/hooks/info.ts
> feat: add 'malagu info' command(temporarily only supports tencent-scf)

- packages/fc-adapter/src/hooks/cli.ts
- packages/fc-adapter/src/hooks/info.ts
- packages/scf-adapter/src/hooks/info.ts
> feat: add 'malagu info' command(support ali-fc)

- packages/scf-adapter/src/hooks/deploy.ts
> fix(scf-adapter)  fix custom domain api call error

- dev-packages/frameworks/src/frameworks.ts
frontend framework deploy support svelte, preact, ember
> feat(framework): frontend framework deploy support svelte, preact, ember

- plugins/node-plugin/src/hooks/props.ts
当项目目标有 backend， 则提供 packge.json main 字段去指定 node.js 入口启动文件的能力。
> feat(node-plugin): appoint entry from package.json main field

- dev-packages/cli-service/package.json
- dev-packages/cli-service/src/webpack/config/plugin-config-factory.ts
fix(cli-service) Fix problems introduced by webpack upgrade
> fix(cli-service) Fix problems introduced by webpack upgrade

- dev-packages/frameworks/src/frameworks.ts
1. 修复 ionic-reac、ionic-angular 框架识别错误的问题
2. 去除 svelteKit 的默认支持
3. 优化 svelte 匹配规则
> fix(frameworks): 修复 ionic-reac、ionic-angular 框架识别错误的问题

- plugins/lambda-plugin/src/hooks/deploy.ts
This error happens when the role is invalid (which is not the case) or when you try to create the Lambda function just after the role creation.
Amazon needs a few seconds to replicate your new role through all regions.
View detail: `https://stackoverflow.com/questions/37503075/invalidparametervalueexception-the-role-defined-for-the-function-cannot-be-assu`
> fix(lambda-plugin): 修复 lambda 创建新函数有几率因为新角色未同步导致报错的问题

- package.json
- packages/grommet/src/browser/theme/theme-context.tsx
- packages/react/src/browser/context/index.ts
- packages/react/src/browser/locale/locale-context.tsx
- packages/react/src/browser/router/index.ts
- packages/shell/src/browser/layout/layout.tsx
- yarn.lock
> fix(typedoc) 修复文档生成死循环

- configs/typedoc.json
- tsconfig.json
> fix(typedoc) 修复文档输出格式

- CHANGELOG.md
- packages/core/src/common/application/application-factory.ts
- packages/core/src/common/config/config-util.ts
- packages/core/src/common/utils/global-util.ts
修改 globalThis 为 currentThis，解决globalThis带来的变量提升问题
> fix(core) 修改 globalThis 为 currentThis

- dev-packages/cli-common/src/env/env.ts
- dev-packages/cli-common/src/packager/pnpm.ts
- dev-packages/cli-common/src/packager/utils.ts
- dev-packages/cli-service/src/external/pack-external-module.ts
- dev-packages/cli/src/init/init-manager.ts
- dev-packages/cli/src/malagu.ts
- plugins/code-loader-plugin/src/code-loader.ts
> feat(cli): add pnpm Packager

- dev-packages/cli-common/src/packager/utils.ts
> fix(cli): change packager detect order

- dev-packages/cli-service/src/external/pack-external-module.ts
> fix(cli-service):  get real npm package name

- examples/adonis-app/package.json
- plugins/node-plugin/src/hooks/props.ts
> fix(adonis): entry undifined error

- plugins/fc-plugin/src/hooks/deploy.ts
> feat(fc-plugin): add http trigger url

- dev-packages/cli-common/src/packager/pnpm.ts
> feat(pnpm): add copyPackageSectionNames

- dev-packages/cli-common/src/packager/packager-protocol.ts
- dev-packages/cli-common/src/packager/pnpm.ts
https://github.com/cellbang/malagu/issues/182
> feat(cli-common): support pnpm workspace

- packages/vue/package.json
- packages/vue/src/hooks/webpack.ts
- yarn.lock
将vue-style-loader替换为style-loader
> feat(vue) 将vue-style-loader替换为style-loader

- CHANGELOG.md
- packages/oauth2-core/src/node/endpoint/access-token-response-converter.ts
fix(oauth2-core) 修复 tokenResponse 转换错误
> fix(oauth2-core) 修复 tokenResponse 转换错误

- CHANGELOG.md
- packages/oauth2-client/malagu.yml
- packages/oauth2-client/src/node/authorization/authorization-code-grant-middleware.ts
- packages/oauth2-client/src/node/constants.ts
修复 AuthorizationCodeGrantMiddleware 中间件中 AuthorizationResponse 判定逻辑
> 修复 AuthorizationCodeGrantMiddleware 中间件中 AuthorizationResponse 判定逻辑

- .node-version
- CHANGELOG.md
- dev-packages/cli-runtime/runtimes/default/malagu-bun-baseline.yml
- dev-packages/cli-runtime/runtimes/default/malagu-node18.yml
- dev-packages/cli-runtime/runtimes/default/malagu-node20.yml
https://github.com/cellbang/malagu/issues/199
> feat(cli-runtime): add node18, node20, bun runtime

- dev-packages/cli-service/package.json
- dev-packages/cli-service/src/hooks/start-dev-server.ts
- examples/vitesse-app/eslint.config.js
- examples/vitesse-app/package.json
- examples/vitesse-app/src/browser/main.ts
- examples/vitesse-app/src/browser/module.ts
- examples/vitesse-app/src/browser/pages/hi/[name].vue
- examples/vitesse-app/src/browser/pages/index.vue
- examples/vitesse-app/src/browser/router.ts
- examples/vitesse-app/src/browser/shims.d.ts
- examples/vitesse-app/src/common/welcome-protocol.ts
- examples/vitesse-app/src/node/module.ts
- examples/vitesse-app/src/node/welcome-server.ts
- examples/vitesse-app/src/webpack-hook.ts
- examples/vitesse-app/tsconfig.json
- yarn.lock
这次更改之后，所有项目中的package.json都可以设置为type: module而不报错了，可喜可贺🎉
> refactor: 更改start-dev-server相关逻辑，将require改成使用importx-tsup进行导入
